apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimcall.fullname" . }}-secrets
  labels:
    {{- include "heimcall.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- range $name, $svc := .Values.services }}
  {{- if $svc.db }}
  {{- $creds := index (default (dict) $.Values.secrets.db) $name | default (dict) }}
  {{ $name }}-db-username: {{ default $svc.db $creds.username | quote }}
  {{ $name }}-db-password: {{ default $svc.db $creds.password | quote }}
  {{- end }}
  {{- end }}
