{{- $root := . }}
{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "heimcall.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ default "ClusterIP" $svc.serviceType }}
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
---
{{- end }}
