server:
  port: 8084

spring:
  application:
    name: service-catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/catalog}
    username: ${DB_USERNAME:catalog}
    password: ${DB_PASSWORD:catalog}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

identity:
  base-url: ${IDENTITY_BASE_URL:http://localhost:8083}

escalation:
  base-url: ${ESCALATION_BASE_URL:http://localhost:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info
