package com.urunsiyabend.heimcall.common.outbox;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import org.apache.kafka.common.TopicPartition;
import org.apache.kafka.common.errors.TimeoutException;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.support.SendResult;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.CompletableFuture;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Phase 15 T1 — poison-row dead-lettering. Proves the relay no longer suffers a head-of-line stall:
 * a row that can never be relayed is flagged {@code DEAD} and the rows behind it keep flowing.
 *
 * <p>Two failure modes are covered: a <b>pre-send</b> poison (corrupt {@code headers} JSON, dead-lettered
 * immediately) and a <b>transient</b> failure (broker timeout, kept PENDING and retried, then dead-lettered
 * only after it burns through {@code maxAttempts} — the backstop for an unforeseen always-failing row).
 *
 * <p>Runs against the local docker-compose PostgreSQL (override via {@code OUTBOX_TEST_JDBC_URL} /
 * {@code _USER} / {@code _PASSWORD}); isolated in a dedicated schema. Skips if no PG is reachable.
 */
class OutboxRelayPoisonRowTest {

    private static final String URL = envOr("OUTBOX_TEST_JDBC_URL", "jdbc:postgresql://localhost:5433/incident");
    private static final String USER = envOr("OUTBOX_TEST_JDBC_USER", "incident");
    private static final String PASS = envOr("OUTBOX_TEST_JDBC_PASSWORD", "incident");
    private static final String SCHEMA = "outbox_poison_test";

    private static String envOr(String key, String fallback) {
        String v = System.getenv(key);
        return v != null ? v : fallback;
    }

    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() throws Exception {
        Connection probe;
        try {
            probe = DriverManager.getConnection(URL, USER, PASS);
        } catch (SQLException unreachable) {
            assumeTrue(false, "No PostgreSQL at " + URL + " (set OUTBOX_TEST_JDBC_URL); skipping");
            return;
        }
        try (Connection c = probe; Statement st = c.createStatement()) {
            st.execute("DROP SCHEMA IF EXISTS " + SCHEMA + " CASCADE");
            st.execute("CREATE SCHEMA " + SCHEMA);
            // Mirror the production outbox columns the relay reads/writes.
            st.execute("CREATE TABLE " + SCHEMA + ".outbox ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "aggregate_id TEXT NOT NULL, topic TEXT NOT NULL, msg_key TEXT, "
                    + "payload BYTEA NOT NULL, headers TEXT NOT NULL, "
                    + "status TEXT NOT NULL DEFAULT 'PENDING', attempts INT NOT NULL DEFAULT 0, "
                    + "last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), published_at TIMESTAMPTZ)");
        }
        DriverManagerDataSource ds = new DriverManagerDataSource(URL, USER, PASS);
        ds.setSchema(SCHEMA);
        this.jdbc = new JdbcTemplate(ds);
    }

    @AfterEach
    void tearDown() {
        try (Connection c = DriverManager.getConnection(URL, USER, PASS); Statement st = c.createStatement()) {
            st.execute("DROP SCHEMA IF EXISTS " + SCHEMA + " CASCADE");
        } catch (SQLException ignored) {
            // best effort
        }
    }

    private void insert(long id, String agg, String headers) {
        jdbc.update("INSERT INTO outbox (id, aggregate_id, topic, msg_key, payload, headers) "
                + "VALUES (?, ?, 'incident.lifecycle.v1', ?, ?, ?)", id, agg, agg, new byte[]{0}, headers);
    }

    private String status(long id) {
        return jdbc.queryForObject("SELECT status FROM outbox WHERE id = ?", String.class, id);
    }

    private int attempts(long id) {
        return jdbc.queryForObject("SELECT attempts FROM outbox WHERE id = ?", Integer.class, id);
    }

    @Test
    @SuppressWarnings("unchecked")
    void corruptHeadersRowIsDeadLetteredAndGoodRowFlows() {
        assumeTrue(jdbc != null, "no PG");
        insert(1, "X", "{ this is not json");  // poison: corrupt headers, aggregate X
        insert(2, "Y", "{}");                  // good, aggregate Y

        KafkaTemplate<String, byte[]> kafka = mock(KafkaTemplate.class);
        SendResult<String, byte[]> ok = new SendResult<>(null,
                new RecordMetadata(new TopicPartition("incident.lifecycle.v1", 0), 0, 0, 0, 0, 0));
        when(kafka.send(any(ProducerRecord.class))).thenReturn(CompletableFuture.completedFuture(ok));
        SimpleMeterRegistry meters = new SimpleMeterRegistry();

        OutboxRelay relay = new OutboxRelay(jdbc, kafka, new ObjectMapper(), 10, 1000, 10, meters);
        relay.relay();

        // Poison row dead-lettered; good row published in the SAME round (continue, not break).
        assertThat(status(1)).isEqualTo("DEAD");
        assertThat(attempts(1)).isEqualTo(1);
        assertThat(status(2)).isEqualTo("PUBLISHED");
        verify(kafka, times(1)).send(any(ProducerRecord.class));  // only the good row reached the broker
        assertThat(meters.counter("outbox_dead_total").count()).isEqualTo(1.0);
    }

    @Test
    @SuppressWarnings("unchecked")
    void rowSpecificTransientFailureDeadLettersAfterMaxAttemptsWhileGoodRowsFlow() {
        assumeTrue(jdbc != null, "no PG");
        insert(1, "X", "{}");  // transient-failing, aggregate X
        insert(2, "Y", "{}");  // good, aggregate Y

        KafkaTemplate<String, byte[]> kafka = mock(KafkaTemplate.class);
        SendResult<String, byte[]> ok = new SendResult<>(null,
                new RecordMetadata(new TopicPartition("incident.lifecycle.v1", 0), 0, 0, 0, 0, 0));
        // Aggregate X always fails with a transient broker TimeoutException (NOT a permanent rejection);
        // every other aggregate succeeds — so the broker is demonstrably reachable each poll.
        when(kafka.send(any(ProducerRecord.class))).thenAnswer(inv -> {
            ProducerRecord<String, byte[]> r = inv.getArgument(0);
            return "X".equals(r.key())
                    ? CompletableFuture.failedFuture(new TimeoutException("broker down"))
                    : CompletableFuture.completedFuture(ok);
        });
        SimpleMeterRegistry meters = new SimpleMeterRegistry();
        OutboxRelay relay = new OutboxRelay(jdbc, kafka, new ObjectMapper(), 10, 1000, 3, meters);

        // Poll 1: pipelined — the good row publishes the SAME round (no head-of-line starvation), and
        // because the broker is reachable (Y succeeded) the failing row X is counted toward the backstop.
        relay.relay();
        assertThat(status(2)).isEqualTo("PUBLISHED");
        assertThat(status(1)).isEqualTo("PENDING");
        assertThat(attempts(1)).isEqualTo(1);

        // A fresh good row each poll keeps the broker visibly reachable, so X keeps accruing attempts.
        insert(3, "Z", "{}");
        relay.relay();
        assertThat(status(3)).isEqualTo("PUBLISHED");
        assertThat(attempts(1)).isEqualTo(2);

        insert(4, "W", "{}");
        relay.relay();  // attempts hits maxAttempts(3) -> backstop dead-letters X
        assertThat(status(4)).isEqualTo("PUBLISHED");
        assertThat(status(1)).isEqualTo("DEAD");
        assertThat(attempts(1)).isEqualTo(3);
        assertThat(meters.counter("outbox_dead_total").count()).isEqualTo(1.0);
    }

    @Test
    @SuppressWarnings("unchecked")
    void brokerBlackoutLeavesAllRowsPendingWithoutDeadLettering() {
        assumeTrue(jdbc != null, "no PG");
        insert(1, "X", "{}");
        insert(2, "Y", "{}");

        KafkaTemplate<String, byte[]> kafka = mock(KafkaTemplate.class);
        // Total outage: every send fails transiently, nothing succeeds in the batch.
        when(kafka.send(any(ProducerRecord.class)))
                .thenReturn(CompletableFuture.failedFuture(new TimeoutException("broker down")));
        SimpleMeterRegistry meters = new SimpleMeterRegistry();
        OutboxRelay relay = new OutboxRelay(jdbc, kafka, new ObjectMapper(), 10, 1000, 3, meters);

        // Several polls of full blackout must NOT bleed the backlog into DEAD: with no success in the
        // batch the relay can't tell a poison row from an outage, so it leaves every row PENDING untouched
        // (no attempt bump, no DEAD). When the broker recovers the whole backlog drains — no row is lost.
        relay.relay();
        relay.relay();
        relay.relay();
        relay.relay();
        assertThat(status(1)).isEqualTo("PENDING");
        assertThat(status(2)).isEqualTo("PENDING");
        assertThat(attempts(1)).isEqualTo(0);
        assertThat(attempts(2)).isEqualTo(0);
        assertThat(meters.counter("outbox_dead_total").count()).isEqualTo(0.0);
    }
}
