-- Phase 9 T2: transactional outbox. notification.delivered / notification.failed events are appended
-- here in the same transaction as the delivery state change (no ghost on rollback, no loss after
-- commit); a scheduled relay publishes PENDING rows to Kafka with confirm and marks them PUBLISHED.
-- Published rows are kept as an audit/replay trail and pruned by a retention window. id is a monotonic
-- identity so the relay can publish in insertion order (per-aggregate ordering preserved).
CREATE TABLE outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    topic          VARCHAR(255) NOT NULL,
    msg_key        VARCHAR(255),
    payload        BYTEA        NOT NULL,
    headers        TEXT         NOT NULL,
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts       INTEGER      NOT NULL DEFAULT 0,
    last_error     TEXT,
    created_at     TIMESTAMPTZ  NOT NULL,
    published_at   TIMESTAMPTZ
);

-- Relay claim path: PENDING rows ordered by id. Partial index keeps it cheap as published rows pile up.
CREATE INDEX ix_outbox_pending ON outbox (id) WHERE status = 'PENDING';

-- Prune path: published rows by age.
CREATE INDEX ix_outbox_published_at ON outbox (published_at) WHERE status = 'PUBLISHED';
