-- Phase 17 T2: transactional outbox for service-catalog. The routing ruleset snapshot is appended
-- here in the same transaction as the rule write (no ghost on rollback, no loss after commit); the
-- common-outbox relay publishes PENDING rows to Kafka and marks them PUBLISHED. Published rows are kept
-- as an audit/replay trail and pruned by a retention window. id is a monotonic identity so the relay
-- publishes in insertion order (per-aggregate ordering preserved). Identical shape to the other
-- services' outbox so the shared relay/appender work unchanged.
CREATE TABLE outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    topic          VARCHAR(255) NOT NULL,
    msg_key        VARCHAR(255),
    payload        BYTEA        NOT NULL,
    headers        TEXT         NOT NULL,
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts       INTEGER      NOT NULL DEFAULT 0,
    last_error     TEXT,
    created_at     TIMESTAMPTZ  NOT NULL,
    published_at   TIMESTAMPTZ
);

CREATE INDEX ix_outbox_pending ON outbox (id) WHERE status = 'PENDING';
CREATE INDEX ix_outbox_published_at ON outbox (published_at) WHERE status = 'PUBLISHED';
